### ISSUE TITLE
Setup Travis CI using linux machine

### ISSUE THREAD

**Issue by Shamash2014** [SwifterSwift/SwifterSwift-Linux#1]
A good reference how one can organize test files for for [XCTest](https://github.com/apple/swift-package-manager/blob/master/Tests/LinuxMain.swift)

- [x] -  Add travic CI integrations with linux machine 
- [x] -  Start porting extensions from the main repo: SwiftStdlib

**Comment by omaralbeik** [comment]
Thank you @Shamash2014 for taking care of this 👍
